<?php   
$oid     =$row['oid'];
$oprog   =$row['oprog'];
$ostat   =$row['ostat'];
$ocod    =$row['ocod'];
$odes    =$row['odes']; 
$otmp    =$row['otmp'];
$otit_sn  =$row['otit_sn'];
$otit     =$row['otit'];		// + 23.03.21
$otext    =$row['otext'];		// + 23.03.21
$oimg1    =$row['oimg1']; 
$otit1    =$row['otit1'];
$otext1   =$row['otext1'];
$olink1   =$row['olink1'];
$oimg2    =$row['oimg2']; 
$otit2    =$row['otit2'];
$otext2   =$row['otext2'];
$olink2   =$row['olink2'];
$oimg3    =$row['oimg3']; 
$otit3    =$row['otit3'];
$otext3   =$row['otext3'];
$olink3   =$row['olink3'];
$oimg4    =$row['oimg4']; 
$otit4    =$row['otit4'];
$otext4   =$row['otext4'];
$olink4   =$row['olink4'];
$osino1	=$row['osino1'];
$osino2	=$row['osino2'];
$osino3	=$row['osino3'];
$osino4	=$row['osino4'];
?>
