<?php
$tid      	=$_POST['tid'];
$tprog    	=$_POST['tprog'];
$tstat    	=$_POST['tstat'];
$tcod     	=$_POST['tcod'];
$tsel     	=$_POST['tsel'];
$ttipo    	=$_POST['ttipo'];
$tfolder  	=$_POST['tfolder']; 
$tdesc    	=addslashes($_POST['tdesc']); 
$tmenu    	=addslashes($_POST['tmenu']);
$tlang    	=$_POST['tlang'];
$tcolor   	=$_POST['tcolor'];
// slide
$tslidebutt    =$_POST['tslidebutt'];
$tslidetime    =$_POST['tslidetime'];
// portfolio 
$tportitle     =$_POST['tportitle'];
$tportit      =$_POST['tportit'];
$tportext     =addslashes($_POST['tportext']);
// glifi
$tglyforma     =$_POST['tglyforma'];
$tgliftitle    =$_POST['tgliftitle'];
$tgliftit      =$_POST['tgliftit'];
$tgliftext     =addslashes($_POST['tgliftext']);
$tglyreverse   =$_POST['tglyreverse'];
// promo
$tpromotitle   =$_POST['tpromotitle'];
$tpromotit     =$_POST['tpromotit'];
$tpromotext    =addslashes($_POST['tpromotext']);
// contatti
$tcttitle   =$_POST['tcttitle'];
$tcttit     =$_POST['tcttit'];
$tcttext     =addslashes($_POST['tcttext']);  
// accordion
$taccotitle   	=$_POST['taccotitle'];
$taccotit     	=$_POST['taccotit'];
$taccotext     	=addslashes($_POST['taccotext']);
// tab
$ttabtitle   	=$_POST['ttabtitle'];
$ttabtit     	=$_POST['ttabtit'];
$ttabtext     	=addslashes($_POST['ttabtext']); 
// articoli in slide
$tsldtitle   	=$_POST['tsldtitle'];
$tsldtit     	=$_POST['tsldtit'];
$tsldtext     	=addslashes($_POST['tsldtext']);
?>
